### ISSUE TITLE
Error loading module with companion-2.0.0-6994405-1770-win64

### ISSUE THREAD

**Issue by EventReplay** [bitfocus/companion-module-qlab-advance#1]
17. 18:32:42 module(qlab-advance): Error loading module: Error: Could not locate the bindings file. Tried: → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\build\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\build\Debug\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\build\Release\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\out\Debug\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\Debug\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\out\Release\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\Release\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\build\default\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\compiled\8.9.3\win32\x64\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node → C:\Program Files\Companion\resources\app.asar\lib\module\qlab-advance\node_modules\@serialport\bindings\lib\binding\node-v57-win32-x64\bindings.node

**Comment by JeffreyDavidsz** [comment]
mmm that's new, running from dev works fine but in the build I see the error. @haakonnessjoen any thoughts?

**Comment by JeffreyDavidsz** [comment]
This is from the log:
`18. 06:44:37 module(qlab-advance): Error loading module: Error: A dynamic link library (DLL) initialization routine failed. \\?\C:\Users\JeffreyDavidsz\AppData\Local\Temp\2d5085fc-8691-4622-82b5-61354fcc419d.tmp.node`

**Comment by JeffreyDavidsz** [comment]
mmmm yarn.lock was in .gitignore?

**Comment by istnv** [comment]
My error. I'm still learning npm/yarn/git and which files needed to be included with the module.

**Comment by JeffreyDavidsz** [comment]
Could you test the latest to see if this is fixed now?

**Comment by EventReplay** [comment]
@JeffreyDavidsz 
companion-2.0.0-445e71b-1771-win64, same error for me, this error is actually on a Win7 machine! (Just used for a quick test of another module)
I have also installed on a Win10 machine to ensure it wasn't just Win7, it has an error same as your previous posted from log.

**Comment by JeffreyDavidsz** [comment]
@EventReplay can you run it like `node headless.js lo` after you did a `./tools/update.sh`? Something is going wrong in the build, because in wsl it runs with no errors

**Comment by EventReplay** [comment]
@JeffreyDavidsz 
Yes worked fine no errors with wsl. Thanks

**Comment by JeffreyDavidsz** [comment]
@haakonnessjoen could you check this? Running it building works fine. But the official build seems to get errors

**Comment by jifop** [comment]
I have two win 10 installations and am getting this error on one but not the other. 

How do I fix it?

**Comment by jifop** [comment]
> Could you check the latest version please? builds.bitfocus.io. Let me know if the problem still is there

I'm using 2.0.0-f03c82c-1847-win64.exe and it's still there.

**Comment by istnv** [comment]
Looking into the windows comment on facebook yesterday, I loaded a recent windows build 2.0.0 (90725f8). It's still getting the loading module/dll error. 
Further research:
qlab-advance depends on osc ^2.3.0 for proper tcp control, which in turn,
depends on a newer serialport module as part of the SLIP support.
Running under a dev build, all dependencies get imported and rebuilt so everything works.
Generating an electron package uses electron's _built-in_ modules, which may not be up to date.

**Comment by EventReplay** [comment]
Thanks @istnv for diagnosing the problem.

I'll close this.
