### ISSUE TITLE
setInterval can be overwritten

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-qlab-advance#11]
If there's multiple updates coming in, the interval will be overwritten. Please make sure to clear the interval if it exists, before creating a new one.

https://github.com/bitfocus/companion-module-qlab-advance/blob/f823295ceb5cdf4c0fb3bbadcabe2b788653a2e6/qlabfb.js#L845

**Comment by istnv** [comment]
I'll add a sanity check, but it should be off before then. 
Existing code should clear the interval on errors, close, and when QLab disconnects. 
Note that this is **not** the QLab 'update' push, which doesn't include playback timers.
There is only one place this 'updates' (note plural) response comes from QLab, and only if there is an open workspace. When QLab acknowledges an open workspace, this starts the interval.

**Comment by istnv** [comment]
updated:
https://github.com/bitfocus/companion-module-qlab-advance/pull/10#issuecomment-554570889
