### ISSUE TITLE
{Enhancement} Dynamic variables for cue names from cue numbers

### ISSUE THREAD

**Issue by GeoDerp** [bitfocus/companion-module-qlab-advance#15]
### Dynamic variables for cue names from cue numbers
Have the ability to have a name instance variable from cue number (for things like button titles).

### Example:
*Cue 5 = Test123*

```$(INSTANCENAME:r_name_5)```

Will spit out the number cue 5's name: **Test123**

### Reason why this is useful: 
As cues have dynamic numbers and the cues themselves may change constantly, this will allow for the ability of a companion title to always be showing the correct name of cue that you will be running. 

So if we change the cue 5 to another video for instance. I can see on companion that the video has changed since the title has changed to the correct name of that video. 

(let me know if it needs more explanation)

**Comment by willosof** [comment]
How does this module handle when multiple cues are playing?

**Comment by istnv** [comment]
Already implemented as $(INSTANCENAME:q_{num}_name). 
Details (and restrictions) are on the help screen.

**Comment by GeoDerp** [comment]
> Already implemented as $(INSTANCENAME:q_{num}_name).
> Details (and restrictions) are on the help screen.

DOPE, thank so much, must of not saw that variable when I was looking.
